# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wrplpTAIndJjJRXTvKyyQyrSzmhN609o
"""

numb = input("enter numbers: ")
for i in numb:
  if i == 's':
    print("enter a valid number")
    break

    

Mks = list(map(int, numb.split())) 
print(Mks)
leng = len(Mks)
print("amount of subjects", leng)



    
def bubbleSortAc(Mks):
    for num in range(len(Mks)-1,0,-1):
        for i in range(num):
            if Mks[i]>Mks[i+1]:
                temp = Mks[i]
                Mks[i] = Mks[i+1]
                Mks[i+1] = temp


bubbleSortAc(Mks)
print(Mks)
  
def bubbleSortDc(Mks):
    for num in range(len(Mks)-1,0,-1):
        for i in range(num):
            if Mks[i]<Mks[i+1]:
                temp = Mks[i]
                Mks[i] = Mks[i+1]
                Mks[i+1] = temp

bubbleSortDc(Mks)
print(Mks)