# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TxIIPJnJ_sPWv_MZI586g_-HNOTh2xzr
"""

import time
import datetime

print("Current date and time: " , datetime.datetime.now())

import hijri_converter
from datetime import datetime
from hijri_converter import Gregorian, Hijri, convert

# Prompt the user for a date in the format %Y-%m-%d
date_str = (input('Enter a date in the format %Y-%m-%d: '))

# Parse the date string and convert it to a Gregorian date object
date_conv = datetime.strptime(date_str, '%Y-%m-%d')


# Convert the Gregorian date to a Hijri date
hijri_date = convert.Gregorian.fromdate(date_conv).to_hijri()

# Print the Hijri date
print("normal date: ",date_conv)
print("Hijiri Date:",hijri_date)